# Generated by Django 4.2.20 on 2025-03-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0012_alter_company_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
