# Generated by Django 4.2.20 on 2025-04-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0014_company_twitter_url_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('premium', 'Premium')], default='normal', max_length=10),
        ),
    ]
