# Generated by Django 5.1.4 on 2025-04-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0017_company_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_at',
        ),
    ]
